web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./var/htdocs:/wwwroot
    - ./etc/nginx.docker.config:/etc/nginx/conf.d/site.conf
  links:
    - php
php:
  image: php:7-fpm
  volumes:
    - ./var/htdocs:/wwwroot
